### ISSUE TITLE
Add tax metrics

### ISSUE THREAD

**Issue by amal** [PVGorshenin/country_comparison#14]
Can you add some tax metrics to the table, please?

Some of the potential metrics and sources for them:

- Personal Income Tax Rate: The percentage of income individuals pay in taxes.
  - https://data.oecd.org/tax/tax-on-personal-income.htm
  - https://taxfoundation.org/data/global-tax/
  - https://data.stanford.edu/citd

- Value Added Tax (VAT / consumption) Rate: The percentage added to the value of goods and services at each stage of production or distribution.
  - https://worldpopulationreview.com/country-rankings/vat-tax-by-country
  - https://taxfoundation.org/data/all/eu/value-added-tax-2023-vat-rates-europe/
  - https://taxsummaries.pwc.com/quick-charts/value-added-tax-vat-rates
  - https://www.globalvatcompliance.com/globalvatnews/world-countries-vat-rates-2020/
  - https://www.oecd.org/tax/consumption/consumption-tax-trends-19990979.htm

- Property taxes
  - https://data.oecd.org/tax/tax-on-property.htm

- Corporate Tax Rate: The percentage of profits that corporations are taxed.
  - https://taxfoundation.org/data/all/global/corporate-tax-rates-by-country-2023/
  - https://www.oecd.org/tax/tax-policy/corporate-tax-statistics-database.htm
  - https://taxsummaries.pwc.com/quick-charts/corporate-income-tax-cit-rates
  - https://www.investopedia.com/articles/personal-finance/051915/corporate-tax-rates-highs-and-lows.asp
  - https://tradingeconomics.com/country-list/corporate-tax-rate

- Tax-to-GDP Ratio: The ratio of tax revenue collected by the government to the country's Gross Domestic Product (GDP).
  - Available in OECD reports

**Comment by PVGorshenin** [comment]
Привет! В эту итерацию точно не возмусь. Хотя очень важный индикатор.

Налоги слишком сложная и объёмная тема. Хотелось бы получать one-number metric, но даже с физиками это сложно. Тот же подоходный не даёт всей картины. Важна сумма отчислений в целом: подоходный, медицина, пенсионные отчисления, прочие виды налогов. Доля отчислений между налогплательщиком и работадателем в разных странах разная. Часто ставка налогов не фиксированная (например в Германии), а зависит от семейного положения и уровня доходов. На финальную величину будет влиять возможность вычета за отдельные виды услуг. 

Вангую ещё что более-менее релевантные цифры будут для небольшого числа стран. Сомневаюсь, что все 83 страны получится покрыть.

**Comment by amal** [comment]
@PVGorshenin ещё интересный индикатор - свобода интернета.

С ним кажется данные не очень сложные и сразу по множеству стран:
https://freedomhouse.org/countries/freedom-net/scores?sort=desc&order=Total%20Score%20and%20Status

**Comment by PVGorshenin** [comment]
@amal Как раз в этой итераДобавил показатель[ press freedom](https://github.com/PVGorshenin/country_comparison/blob/eba7524645add364c3ea9692158179dacab2e4b1/README.md?plain=1#L30). Он очень сильно скоррелирован со свободой интернета(проверил глазами на нескольких странах)
